// <auto-generated />
namespace SiteSandBox.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class suite : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(suite));
        
        string IMigrationMetadata.Id
        {
            get { return "201401212303554_suite"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
